django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("studens.urls")),
    path('members/', include("django.contrib.auth.urls")),
    path('members/', include("members.urls")),
]

members/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path("login", views.login_user, name='login'),
	path("logout", views.logout_view, name='logout'),
	path("register/", views.register_user, name='register'),

			
	
	]

studens/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path("", views.index, name="index"),
	path("add/", views.add, name="add"),
	path("edit/<int:id>/", views.edit, name="edit"),
	path("delete/<int:id>/", views.delete, name="delete"),
	path("add_Project/", views.add_Project, name="add_Project"),
	path("add_Job_Type/", views.add_Job_Type, name="add_Job_Type"),
	path("add_Stages/", views.add_Stages, name="add_Stages"),
	path("search_Mission/", views.search_Mission, name="search_Mission"),
	path('testing/', views.testing, name='testing'),

]

studens/models.py
from django.db import models
from datetime import date

# Create your models here.
class Projects(models.Model):
	name = models.CharField(max_length=100, unique=True)
	date = models.DateField(default=date.today)
	nots = models.TextField(null=True, blank=True)

	def __str__(self):
		return self.name

class Stages(models.Model):
	name = models.CharField(max_length=100, unique=True)

	def __str__(self):
		return self.name
	
class Job_Type(models.Model):
	name = models.CharField(max_length=100, unique=True)
	m3_day = models.FloatField()

	def __str__(self):
		return self.name
	

class Mission(models.Model):
	unit_choice = (('1', 'متر مكعب'),('2', 'طابوقة'),('3', 'متر مربع'),('4', 'متر طولي'),)
	project_Name = models.ForeignKey(Projects, on_delete=models.CASCADE)
	project_Stage = models.ForeignKey(Stages, on_delete=models.CASCADE)
	project_Job_Type = models.ForeignKey(Job_Type, on_delete=models.CASCADE)
	quantity = models.IntegerField()
	unit = models.CharField(max_length=1, choices=unit_choice)
	start_Date = models.DateField(default=date.today)
	finish_Date = models.DateField(default=date.today)
	number_Of_Days = models.IntegerField()
	number_Of_Hours = models.IntegerField()
	nots = models.TextField(null=True, blank=True)


	@property
	def start_Date_format(self):
		return self.start_Date.strftime("%Y/%m/%d")

	@property
	def finish_Date_format(self):
		return self.finish_Date.strftime("%Y/%m/%d")

	@property
	def production_Ratio(self):
		Hours = self.number_Of_Hours
		Q = self.quantity
		M3 = self.project_Job_Type.m3_day
		P_Ratio = (Q/(M3/2)*(8/Hours))*100
		return f"{P_Ratio:.0f} %"


studens/forms.py
from django import forms
from .models import Projects, Mission, Stages, Job_Type
import datetime

class MissionForm(forms.ModelForm):
	class Meta:
		model = Mission
		fields = ("project_Name", "project_Stage", "project_Job_Type", "quantity", "unit", "start_Date", "finish_Date", "number_Of_Days", "number_Of_Hours", "nots")
		labels = {
			"project_Name" : "اسم المشروع",
			"project_Stage" : "المرحلة المنفذة", 
			"project_Job_Type" : "نوع العمل المنفذ", 
			"quantity" : "الكمية", 
			"unit" : "الوحدة", 
			"start_Date" : "تاريخ البداية", 
			"finish_Date" : "تاريخ الانتهاء", 
			"number_Of_Days" : "عدد الايام", 
			"number_Of_Hours" : "عدد الساعات", 
			"nots" : "ملاحظات"
		}

		widgets = {
			"project_Name" : forms.Select(attrs={"class": "form-control"}),
			"project_Stage" : forms.Select(attrs={"class": "form-control"}),
			"project_Job_Type" : forms.Select(attrs={"class": "form-control"}),
			"quantity" : forms.NumberInput(attrs={"class": "form-control"}), 
			"unit" : forms.Select(attrs={"class": "form-control"}), 
			"start_Date" : forms.SelectDateWidget(attrs={"class": "form-control "},years=[datetime.date.today().year-i for i in range(5)]), 
			"finish_Date" : forms.SelectDateWidget(attrs={"class": "form-control "},years=[datetime.date.today().year-i for i in range(5)]),
			"number_Of_Days" : forms.NumberInput(attrs={"class": "form-control"}), 
			"number_Of_Hours" : forms.NumberInput(attrs={"class": "form-control"}), 
			"nots" : forms.Textarea(attrs={"class": "form-control"})
		}

class ProjectsForm(forms.ModelForm):
	class Meta:
		model = Projects
		fields = ("name", "date", "nots")
		labels = {
			"name" : "إسم المشروع",
			"date" : "تاريخ الاستلام", 
			"nots" : "ملاحظات"
		}

		widgets = {
			"name" : forms.TextInput(attrs={"class": "form-control"}),
			"date" : forms.SelectDateWidget(attrs={"class": "form-control "},years=[datetime.date.today().year-i for i in range(5)]),
			"nots" : forms.Textarea(attrs={"class": "form-control"})
		}

class StagesForm(forms.ModelForm):
	class Meta:
		model = Stages
		fields = ("name", )
		labels = {
			"name" : "اسم المرحلة",
		}

		widgets = {
			"name" : forms.TextInput(attrs={"class": "form-control"}),

		}


class Job_TypeForm(forms.ModelForm):
	class Meta:
		model = Job_Type
		fields = ("name", "m3_day")
		labels = {
			"name" : "اسم العمل المنفذ",
			"m3_day" : "معدل الانجاز في اليوم", 
		}

		widgets = {
			"name" : forms.TextInput(attrs={"class": "form-control"}),
			"m3_day" : forms.NumberInput(attrs={"class": "form-control"})
		}

studens/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.urls import reverse
from django.template import loader
from . models import Projects, Mission, Stages, Job_Type
from . forms import MissionForm, ProjectsForm, StagesForm, Job_TypeForm
import datetime

def index(request):
	return render(request, "studens/index.html", {
		"Mission": Mission.objects.order_by("-finish_Date")[:10],
		})

def search_Mission(request):
	x = datetime.date.today().month
	y = datetime.date.today().year
	input_month = x if ((request.POST.get("input_month", False)) == 0) else  request.POST.get("input_month", False)
	input_year = y if ((request.POST.get("input_year", False))== 0) else request.POST.get("input_year", False)

	return render(request, "studens/search_Mission.html", {
		"searched": Mission.objects.filter(finish_Date__year=input_year).filter(finish_Date__month=input_month),

		})

def add(request):
	if request.method == "POST":
		form = MissionForm(request.POST)
		if form.is_valid():
			new_project_Name = form.cleaned_data["project_Name"]
			new_project_Stage = form.cleaned_data["project_Stage"]
			new_project_Job_Type = form.cleaned_data["project_Job_Type"]
			new_quantity = form.cleaned_data["quantity"]
			new_unit = form.cleaned_data["unit"]
			new_start_Date = form.cleaned_data["start_Date"]
			new_finish_Date = form.cleaned_data["finish_Date"]
			new_number_Of_Days = form.cleaned_data["number_Of_Days"]
			new_number_Of_Hours = form.cleaned_data["number_Of_Hours"]
			new_nots = form.cleaned_data["nots"]

			new_missiom = Mission(
				project_Name = new_project_Name,
				project_Stage = new_project_Stage,
				project_Job_Type = new_project_Job_Type,
				quantity = new_quantity,
				unit = new_unit,
				start_Date = new_start_Date,
				finish_Date = new_finish_Date,
				number_Of_Days = new_number_Of_Days,
				number_Of_Hours = new_number_Of_Hours,
				nots = new_nots
				)

			new_missiom.save()
			return render(request, "studens/add.html", {
				"form": MissionForm(),
				"success": True
				})
	else:
		form = MissionForm()
	return render(request, "studens/add.html", {
		"form": MissionForm(),
		
		})

def edit(request, id):
	if request.method == "POST":
		mission = Mission.objects.get(pk=id)
		form = MissionForm(request.POST, instance=mission)
		if form.is_valid():
			form.save()
			return render(request, "studens/edit.html", {
				"form": form,
				"success": True
				})
	else:
		mission = Mission.objects.get(pk=id)
		form = MissionForm( instance=mission)
	return render(request, "studens/edit.html", {
		"form": form
		})

def delete(request, id):
	if request.method == "POST":
		mission = Mission.objects.get(pk=id)
		mission.delete()
	return HttpResponseRedirect(reverse("index"))

# def getYears():
# 	current_date = datetime.date.today()
# 	y = current_date.year
# 	years = [y-i for i in range(5)]
# 	return years

# def getMonthes():
# 	monthes = [i for i in range(1,13)]
# 	return monthes


def add_Project(request):
	if request.method == "POST":
		form = ProjectsForm(request.POST)
		if form.is_valid():
			new_name = form.cleaned_data["name"]
			new_date = form.cleaned_data["date"]
			new_nots = form.cleaned_data["nots"]

			new_projects = Projects(
				name = new_name,
				date = new_date,
				nots = new_nots,
				)

			new_projects.save()
			return render(request, "studens/add_Project.html", {
				"form": ProjectsForm(),
				"success": True
				})
	else:
		form = ProjectsForm()
	return render(request, "studens/add_Project.html", {
		"form": ProjectsForm()
		})

def add_Stages(request):
	if request.method == "POST":
		form = StagesForm(request.POST)
		if form.is_valid():
			new_name = form.cleaned_data["name"]
			new_Stages = Stages(
				name = new_name,
				)
			new_Stages.save()
			return render(request, "studens/add_Stages.html", {
				"form": StagesForm(),
				"success": True
				})
	else:
		form = StagesForm()
	return render(request, "studens/add_Stages.html", {
		"form": StagesForm()
		})

def add_Job_Type(request):
	if request.method == "POST":
		form = Job_TypeForm(request.POST)
		if form.is_valid():
			new_name = form.cleaned_data["name"]
			new_m3_day = form.cleaned_data["m3_day"]

			new_Job_Type = Job_Type(
				name = new_name,
				m3_day = new_m3_day,
				)
			new_Job_Type.save()
			return render(request, "studens/add_Job_Type.html", {
				"form": Job_TypeForm(),
				"success": True
				})
	else:
		form = Job_TypeForm()
	return render(request, "studens/add_Job_Type.html", {
		"form": Job_TypeForm()
		})

def testing(request):
	x = datetime.date.today().month
	y = datetime.date.today().year
	ye= [datetime.date.today().year -i for i in range(5)]
	input_month = x if ((request.POST.get("input_month", False)) == 0) else  request.POST.get("input_month", False)
	input_year = y if (request.POST.get("input_year", False))== 0 else request.POST.get("input_year", False)
	return render(request, "studens/testing.html", {
		'fruits': ['Apple', 'Banana', 'Cherry'],
		"input_month": input_month,
		"input_year": input_year,
		"ye": ye,


		})

studens/templates/studens/add.html
{% extends "studens/base.html" %}
{% block title %}
  اضافة مهمة جديدة
{% endblock %}
{% block body %}

	{% if user.is_authenticated %}
	{% if success %}
	<div class="alert alert-success text-center" role="alert">
		تمت الاضافة بنجاح
		<a href="{% url 'index' %}" class="alert-link">الصفحة الرئيسية</a>
	</div>
	{% else %}
		<div class="row justify-content-center " style="font-size:15px">
			<div class="col-6">
				<div class="card bg-light mb-3">
				<div class="card-header text-center">
					<i class="fa-solid fa-arrow-down-to-arc fa-lg"></i> <strong>تسجيل المهام</strong>
				</div>
				<div class="card-body ">
					<form action="{% url 'add' %}" method="POST">
						{% csrf_token %}
						{% for field in form %}
						<div class="input-group mb-3 row ">
							<div class="col-4 text-center">{{ field.label_tag }}</div>
							
							<div class="col-7">
								<div class="input-group ">
								{{ field }}
								</div>
							</div>
							
							{% if field.html_name == "project_Name" %}
	<a class="btn btn-secondary col-1" href="{% url 'add_Project' %}"><i class="fa-solid fa-plus fa-lg"></i></a>
							{% elif field.html_name == "project_Stage" %}
	<a class="btn btn-secondary col-1" href="{% url 'add_Stages' %}"><i class="fa-solid fa-plus fa-lg"></i></a>
							{% elif field.html_name == "project_Job_Type" %}
	<a class="btn btn-secondary col-1" href="{% url 'add_Job_Type' %}"><i class="fa-solid fa-plus fa-lg"></i></a>
							{% else %}
							{{ pass }}
							{% endif %}

						</div>
						{% endfor %}
						<button type="submit" class="btn btn-primary ">اضافة</button>
						<a href="{% url 'index' %}" class="btn btn-secondary m-3">الغاء</a>
						
					</form>
				</div>
				</div>
			</div>
		</div>
	{% endif %}
	{% else %}
	<div class="text-center">
	<h1>يجب عليك تسجيل الدخول   لاضافة  المهام .....</h1>
	<a class="btn btn-light m-4" href="{% url 'login' %}"><h5>دخول</h5></a>
	</div>
	{% endif %}

{% endblock %}

studens/templates/studens/add_Job_Type.html
{% extends "studens/base.html" %}
{% block title %}
  اضافة نوع العمل
{% endblock %}
{% block body %}
	
	{% if success %}
	<div class="alert alert-success text-center" role="alert">
		تم اضافة نوع عمل جديد
		<a href="{% url 'add' %}" class="alert-link">تسجل المهام</a>
	</div>
	{% else %}
		<div class="row justify-content-center " style="font-size:15px">
			<div class="col-6">
				<div class="card bg-light mb-3">
				<div class="card-header text-center">
					<i class="fa-solid fa-arrow-down-to-arc fa-lg"></i> <strong>اضافة نوع العمل</strong>
				</div>
				<div class="card-body ">
					<form action="{% url 'add_Job_Type' %}" method="POST">
						{% csrf_token %}
						{% for field in form %}
						<div class="input-group mb-3 row ">
							<div class="col-4 text-center">{{ field.label_tag }}</div>
							
							<div class="col-7">
								<div class="input-group ">
								{{ field }}
								</div>
							</div>

						</div>
						{% endfor %}
						<button type="submit" class="btn btn-primary ">اضافة</button>
						<a href="{% url 'add' %}" class="btn btn-secondary m-3">الغاء</a>
						
					</form>
				</div>
				</div>
			</div>
		</div>
	{% endif %}
	
{% endblock %}

studens/templates/studens/add_Project.html
{% extends "studens/base.html" %}
{% block title %}
  اضافة مشروع جدديد
{% endblock %}
{% block body %}
	
	{% if success %}
	<div class="alert alert-success text-center" role="alert">
		تم اضافة مشروع جديد
		<a href="{% url 'add' %}" class="alert-link">تسجل المهام</a>
	</div>
	{% else %}
		<div class="row justify-content-center " style="font-size:15px">
			<div class="col-6">
				<div class="card bg-light mb-3">
				<div class="card-header text-center">
					<i class="fa-solid fa-arrow-down-to-arc fa-lg"></i> <strong>اضافة مشروع</strong>
				</div>
				<div class="card-body ">
					<form action="{% url 'add_Project' %}" method="POST">
						{% csrf_token %}
						{% for field in form %}
						<div class="input-group mb-3 row ">
							<div class="col-4 text-center">{{ field.label_tag }}</div>
							
							<div class="col-7">
								<div class="input-group ">
								{{ field }}
								</div>
							</div>

						</div>
						{% endfor %}
						<button type="submit" class="btn btn-primary ">اضافة</button>
						<a href="{% url 'add' %}" class="btn btn-secondary m-3">الغاء</a>
						
					</form>
				</div>
				</div>
			</div>
		</div>
	{% endif %}
	
{% endblock %}

studens/templates/studens/add_Stages.html
{% extends "studens/base.html" %}
{% block title %}
 اضافة مرحلة
{% endblock %}
{% block body %}
	
	{% if success %}
	<div class="alert alert-success text-center" role="alert">
		تم اضافة مرحلة
		<a href="{% url 'add' %}" class="alert-link">تسجل المهام</a>
	</div>
	{% else %}
		<div class="row justify-content-center " style="font-size:15px">
			<div class="col-6">
				<div class="card bg-light mb-3">
				<div class="card-header text-center">
					<i class="fa-solid fa-arrow-down-to-arc fa-lg"></i> <strong>اضافة مرحلة</strong>
				</div>
				<div class="card-body ">
					<form action="{% url 'add_Stages' %}" method="POST">
						{% csrf_token %}
						{{ form.as_p }}
						<button type="submit" class="btn btn-primary ">اضافة</button>
						<a href="{% url 'add' %}" class="btn btn-secondary m-3">الغاء</a>
						
					</form>
				</div>
				</div>
			</div>
		</div>
	{% endif %}
	
{% endblock %}

studens/templates/studens/edit.html
{% extends "studens/base.html" %}
{% block title %}
  تعديل علي مهمة منفذة
{% endblock %}
{% block body %}
	<!-- <h4 class="text-center m-4">تعديل مهمة منفذة</h4> -->
	{% if user.is_authenticated %}
	{% if success %}
	<div class="alert alert-success text-center" role="alert">
		تم التعديل بنجاح 
		<a href="{% url 'index' %}" class="alert-link">الصفحة الرئيسية</a>
	</div>
	{% else %}
		<div class="row justify-content-center " style="font-size:15px">
			<div class="col-6">
				<div class="card bg-light mb-3">
				<div class="card-header text-center m-4">
					<i class="fa-solid fa-pen-to-square fa-lg"></i><strong> تعديل المهمة</strong>
									</div>
				<div class="card-body">
					<form class="col-auto" action="" method="POST">
						{% csrf_token %}
						
						{% for field in form %}
						<div class="input-group mb-3 row ">
							<div class="col-4 text-center">{{ field.label_tag }}</div>
							<div class="col-7">
							<div class="input-group">{{ field }}</div>
							</div>
						</div>
						{% endfor %}
						
						<button type="submit" class="btn btn-primary ">تعديل</button>
						<a href="{% url 'index' %}" class="btn btn-secondary m-3">الغاء</a>
						
					</form>
				</div>
				</div>
			</div>
		</div>
	{% endif %}
		{% else %}
	<div class="text-center">
	<h1>يجب عليك تسجيل الدخول   لتعديل  المهام .....</h1>
	<a class="btn btn-light m-4" href="{% url 'login' %}"><h5>دخول</h5></a>
	</div>
	{% endif %}
{% endblock %}

studens/templates/studens/index.html
{% extends "studens/base.html" %}

{% block body %}

<!--<h5 class="m-4">جميع المشاريع</h5>-->
		<div class="row">
			<div class="col-12">
				
				<div class="card bg-light">
				  <div class="card-header text-center row">
					
		</div>
				  {% if Mission %}
				  <div class="card-body">
					<p class="card-text">
						<div class="table-responsive">
							<table class="table table-hover table-striped table-bordered table align-middle"> 
							  <thead class="table-light">
								<tr>
								  <th scope="col">اسم المشروع</th>
								  <th scope="col">مرحلة التنفيذ</th>
								  <th scope="col">نوع العمل المنفذ</th>
								  <th scope="col">الكمية </th>
								  <th scope="col">تاريخ البدء</th>
								  <th scope="col">تاريخ الانتهاء</th>
								  <th scope="col">عدد الايام</th>
								  <th scope="col">عدد الساعات</th>
								  <th scope="col">نسبة الانجاز</th>
								  <th scope="col">ملاحظات</th>
								  <th scope="col">Action</th>
								</tr>
							  </thead>
							  <tbody class="table-group-divider">
								{% for jop in Mission %}
								<tr >
									<td>{{ jop.project_Name }}</td>
									<td>{{ jop.project_Stage }}</td>
									<td>{{ jop.project_Job_Type }}</td>
									<td>{{ jop.quantity }} {{jop.get_unit_display}}</td>
									<td>{{ jop.start_Date_format }}</td>
									<td>{{ jop.finish_Date_format }}</td>
									<td>{{ jop.number_Of_Days }} يوم </td>
									<td>{{ jop.number_Of_Hours }} ساعة </td>
									<td style="font-size: 17px">{{ jop.production_Ratio }}</td>
									<td>{{ jop.nots }}</td>
									<td>
										<a class="btn btn-warning me-2" href="{% url 'edit' jop.id %}" ><i class="fa-regular fa-pen-to-square"></i></a>
	{% if user.is_authenticated %}
<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete{{jop.id}}"><i class="fa-solid fa-trash"></i>
</button>
{% else %}
<button type="button" disabled class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete{{jop.id}}"><i class="fa-solid fa-trash"></i>
</button>
{% endif %}
				<!-- her is the modal for delet Mission-->

					<div class="modal" id="delete{{jop.id}}" tabindex="-1" aria-labelledby="myModallabel1" aria-hidden="true">
					  <div class="modal-dialog" role="document">
					    <div class="modal-content">
					      <div class="modal-header">
					        
					        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
					          <span aria-hidden="true"></span>
					        </button>

					      </div>
					      <div class="modal-body text-center">
					      	<h6 class="modal-title">{{jop.project_Job_Type}} {{jop.project_Name}}</h6>
					        <p>هل أنت متأكد من مسح المهمة؟</p>
					      </div>
					      <div class="modal-footer">
					        <form action="{% url 'delete' jop.id %}" method="POST">
					        	{% csrf_token %}
					        	<input type="submit" class="btn btn-primary" value="مسح">
					        </form>
					        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">الغاء</button>
					      </div>
					    </div>
					  </div>
					</div>
				<!--      ................... -->

									</td>
								</tr>
								{% endfor %}
							  </tbody>
							</table>
						</div>
					</p>
				  </div>
				</div>
				{% else %}
				<h5 class="card bg-light ms-4 me-4">لاتوجد مشاريع مضافة</h5>
				{% endif %}
				
		</div>
	</div>

{% endblock %}

studens/templates/studens/search_Mission.html
{% extends "studens/base.html" %}
{% block title %}
  عرض تقرير شهري
{% endblock %}
{% block body %}

<!--<h5 class="m-4">جميع المشاريع</h5>-->
		<div class="row">
			<div class="col-12">
				
				<div class="card bg-light ms-4 me-4 mb-4">
				  <div class="card-header text-center row">
					
		</div>
				  {% if searched %}
				  <div class="card-body">
					<p class="card-text">
						<div class="table-responsive">
							<table class="table table-hover table-striped table-bordered"> 
							  <thead class="table-light">
								<tr>
								  <th scope="col">اسم المشروع</th>
								  <th scope="col">مرحلة التنفيذ</th>
								  <th scope="col">نوع العمل المنفذ</th>
								  <th scope="col">الكمية </th>
								  <th scope="col">تاريخ البدء</th>
								  <th scope="col">تاريخ الانتهاء</th>
								  <th scope="col">عدد الايام</th>
								  <th scope="col">عدد الساعات</th>
								  <th scope="col">نسبة الانجاز</th>
								  <th scope="col">ملاحظات</th>
								  <th scope="col">Action</th>
								</tr>
							  </thead>
							  <tbody class="table-group-divider">
								{% for jop in searched %}
								<tr>
									<td>{{ jop.project_Name }}</td>
									<td>{{ jop.project_Stage }}</td>
									<td>{{ jop.project_Job_Type }}</td>
									<td>{{ jop.quantity }} {{jop.get_unit_display}}</td>
									<td>{{ jop.start_Date_format }}</td>
									<td>{{ jop.finish_Date_format }}</td>
									<td>{{ jop.number_Of_Days }} يوم </td>
									<td>{{ jop.number_Of_Hours }} ساعة </td>
									<td style="font-size: 17px">{{ jop.production_Ratio }}</td>
									<td>{{ jop.nots }}</td>
									<td>
										<a class="btn btn-warning me-1" href="{% url 'edit' jop.id %}" ><i class="fa-regular fa-pen-to-square fa-lg"></i></a>


	{% if user.is_authenticated %}
<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete{{jop.id}}"><i class="fa-solid fa-trash"></i>
</button>
{% else %}
<button type="button" disabled class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete{{jop.id}}"><i class="fa-solid fa-trash"></i>
</button>
{% endif %}
				<!-- her is the modal for delet Mission-->

<div class="modal" id="delete{{jop.id}}" tabindex="-1" aria-labelledby="myModallabel1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"></span>
        </button>

      </div>
      <div class="modal-body text-center">
      	<h6 class="modal-title">{{jop.project_Job_Type}} {{jop.project_Name}}</h6>
        <p>هل أنت متأكد من مسح المهمة؟</p>
      </div>
      <div class="modal-footer">
        <form action="{% url 'delete' jop.id %}" method="POST">
        	{% csrf_token %}
        	<input type="submit" class="btn btn-primary" value="مسح">
        </form>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">الغاء</button>
      </div>
    </div>
  </div>
</div>
				<!--      ................... -->

									</td>
								</tr>
								{% endfor %}
							  </tbody>
							</table>
						</div>
					</p>
				  </div>
				</div>
				{% else %}
				<h5 class="card bg-light ms-4 me-4">لا توجد نتائج </h5>
				{% endif %}
				
		</div>
	</div>

{% endblock %}

studens/templates/studens/testing.html
<!DOCTYPE html>
<html>
<body>

{% for x in ye %}
  <h1>{{ x }}</h1>
{% endfor %}

<p>{{ input_month }} ++++++++++++++++ {{ input_year }}</p>
{% now "Y" as current_year %}

<p>{{ current_year|add:"-2" }}</p>
<!-- ye= [datetime.date.today().year -i for i in range(5)] -->
</body>
</html>